export const PREFERED_THEME = 'PREFERED_THEME';
export const AUTO_COPY_CLIPBOARD_OFF = 'AUTO_COPY_CLIPBOARD_OFF';
export const DEFAULT_MENU = 'DEFAULT_MENU';
export const PRO_DESCRIPTION_ON = 'PRO_DESCRIPTION_ON';

export const JWT_TOKENS = 'JWT_TOKENS';
